apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
        - name: course-app
          image: omar99awaisha/course-services:v1.0
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: crsdbcntr
            - name: DB_USER
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: DB_NAME
              value: coursedb
---
apiVersion: v1
kind: Service
metadata:
  name: course-app
spec:
  selector:
    app:  course-app
  ports:
    - port: 81
      targetPort: 8081
